<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Kpi;
use App\Models\KpiDimensions;

class KpiDimensionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dimensions = [
            'G6-M1' => [
                [
                    'dimensions'   => 'Cost per Student',
                    'description' => 'An efficiency measure adapted from American higher education and is arrived by dividing the total spending on education by the total number of full-time-equivalent students.',
                ],
                [
                    'dimensions'   => 'Primary Reserve Ratio',
                    'description' => "Measures HAU's financial strength, primarily resource sufficiency and flexibility, by comparing expendable net assets to total expenses; Expendable net assets represent those assets that HAU can access relatively quickly and spend to satisfy its debt obligations; This ratio provides a snapshot of financial strength and flexibility by indicating how long HAU could function using its expendable reserves without relying on additional net assets generated by operations.",
                ],
                [
                    'dimensions'   => 'Return on Net Assets Ratio',
                    'description' => "Determines whether HAU is financially better off than previous years by measuring total economic return; This ratio furnishes a broad measure of the change in HAU's total wealth over a single year and is based on the level and change in total net assets, regardless of asset classification; The ratio provides the most comprehensive measure of the growth or decline in total wealth of HAU over a specific period of time.",
                ],
                [
                    'dimensions'   => 'Net Operating Revenues Ratio',
                    'description' => 'Indicator explaining how surplus from operating activities affects the behavior of the other core financial ratios.',
                ],
            ],
            'G10-M2' => [
                [
                    'dimensions'   => 'Christ-Centeredness',
                    'description' => 'Being a witness of the person and example of Jesus.',
                ],
                [
                    'dimensions'   => 'Integrity',
                    'description' => 'Fairness, honesty and transparency in our personal and professional dealings.',
                ],
                [
                    'dimensions'   => 'Community',
                    'description' => 'Animating the spirit of communion and solidarity.',
                ],
                [
                    'dimensions'   => 'Societal Responsibility',
                    'description' => 'Working for economic efficiency, social justice, and environmental stewardship.',
                ],
            ],
        ];

        // Loop through each KPI and insert its dimensions
        foreach ($dimensions as $measureCode => $dimensionList) {
            $kpi = Kpi::where('measure_code', $measureCode)->first();

            if ($kpi) {
                foreach ($dimensionList as $dim) {
                    KpiDimensions::create([
                        'kpi_id' => $kpi->id,
                        'dimensions' => $dim['dimensions'] ?? null,
                        'description' => $dim['description'] ?? null,
                    ]);
                }
            } else {
                echo "No KPI found for measure_code: $measureCode\n";
            }
        }
    }
}
